### ISSUE TITLE
Empty Demo Page

### ISSUE THREAD

**Issue by jlukic** [typescene/typescene-treegrid#1]
Hey, interesting project. I was looking for concrete examples with some UI from the docs and found this repo.

Tried out your demo (following readme instructions) and was getting an empty layout--see below. 

![localhost_1234_(Macbook Pro) (1)](https://user-images.githubusercontent.com/23123/60379249-a1b0b980-99fd-11e9-8534-ad0cfbb37259.png)

**Comment by jcormont** [comment]
Thanks a lot for checking this out, it's fixed now!
